# Generated by Django 4.0 on 2021-12-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
